#!/bin/sh
# Rebuild the development environment - stuff not in Git.
mkdir /mod/dev/tvdiary/sbin.jim

TDIR=/mod/dev/tvdiary/src/sbin
LDIR=/mod/dev/tvdiary/sbin.jim
ln -s $TDIR/tvdiary_status $LDIR/tvdiary_status.jim
ln -s $TDIR/tvdiary_purge $LDIR/tvdiary_purge.jim
ln -s $TDIR/tvdiary_migrate $LDIR/tvdiary_migrate.jim

mkdir /mod/dev/tvdiary/live
mkdir /mod/dev/tvdiary/live/sbin

TDIR=/mod/sbin
LDIR=/mod/dev/tvdiary/live/sbin
ln -s $TDIR/tvdiary_status $LDIR/tvdiary_status
ln -s $TDIR/tvdiary_purge $LDIR/tvdiary_purge
ln -s $TDIR/tvdiary_migrate $LDIR/tvdiary_migrate
ln -s $TDIR/tvdiary_monitor_on $LDIR/tvdiary_monitor_on
ln -s $TDIR/tvdiary_monitor_off $LDIR/tvdiary_monitor_off

mkdir /mod/dev/tvdiary/live/webif
mkdir /mod/dev/tvdiary/live/webif/html
mkdir /mod/dev/tvdiary/live/webif/html/tvdiary

TDIR=/mod/webif/html/tvdiary
LDIR=/mod/dev/tvdiary/live/webif/html/tvdiary
ln -s $TDIR/day_json.jim $LDIR/day_json.jim
ln -s $TDIR/epgsearch_json.jim $LDIR/epgsearch_json.jim
ln -s $TDIR/get_watchlist_cfg_json.jim $LDIR/get_watchlist_cfg_json.jim
ln -s $TDIR/history_json.jim $LDIR/history_json.jim
ln -s $TDIR/index.jim $LDIR/index.jim
ln -s $TDIR/inventory_json.jim $LDIR/inventory_json.jim
ln -s $TDIR/jslog.jim $LDIR/jslog.jim
ln -s $TDIR/monthly_json.jim $LDIR/monthly_json.jim
ln -s $TDIR/script.js $LDIR/script.js
ln -s $TDIR/style.css $LDIR/style.css
ln -s $TDIR/tvdiary_aggregate.jim $LDIR/tvdiary_aggregate.jim
ln -s $TDIR/tvdiary_utils.jim $LDIR/tvdiary_utils.jim
ln -s $TDIR/tvdiary_stub.jim $LDIR/tvdiary_stub.jim
ln -s $TDIR/tvdiary_watchlist.jim $LDIR/tvdiary_watchlist.jim
ln -s $TDIR/update_watchlist_cfg_json.jim $LDIR/update_watchlist_cfg_json.jim
ln -s $TDIR/watchlist_json.jim $LDIR/watchlist_json.jim
ln -s $TDIR/view_analysis.jim $LDIR/view_analysis.jim

mkdir /mod/dev/tvdiary/live/webif/plugin
mkdir /mod/dev/tvdiary/live/webif/plugin/tvdiary

TDIR=/mod/webif/plugin/tvdiary
LDIR=/mod/dev/tvdiary/live/webif/plugin/tvdiary
ln -s $TDIR/menu.hook $LDIR/menu.hook
ln -s $TDIR/settings.hook $LDIR/settings.hook
ln -s $TDIR/toolbar.hook $LDIR/toolbar.hook
ln -s $TDIR/update.jim $LDIR/update.jim

mkdir /mod/dev/tvdiary/live/etc
TDIR=/mod/etc
LDIR=/mod/dev/tvdiary/live/etc
ln -s $TDIR/tvdiary.db $LDIR/tvdiary.db
ln -s $TDIR/tvdiary_watchlist.txt $LDIR/tvdiary_watchlist.txt

mkdir /mod/dev/tvdiary/live/tmp
TDIR=/mod/tmp
LDIR=/mod/dev/tvdiary/live/tmp
echo "" > $TDIR/tvdiary.log
echo "" > $TDIR/tvdiaryjs.log
ln -s $TDIR/tvdiary.log $LDIR/tvdiary.log

mkdir /mod/dev/tvdiary/out
