#!/bin/sh
# Rebuild the development environment - stuff not in Git.
mkdir /mod/dev/tvdiary/sbin.jim

TDIR=/mod/dev/tvdiary/src/sbin
LDIR=/mod/dev/tvdiary/sbin.jim
ln -s $TDIR/tvdiary_status $LDIR/tvdiary_status.jim
ln -s $TDIR/tvdiary_purge $LDIR/tvdiary_purge.jim
ln -s $TDIR/tvdiary_publish $LDIR/tvdiary_publish.jim

mkdir /mod/dev/tvdiary/live
mkdir /mod/dev/tvdiary/live/sbin

TDIR=/mod/sbin
LDIR=/mod/dev/tvdiary/live/sbin
#ln -s $TDIR/tvdiary_status $LDIR/tvdiary_status
#ln -s $TDIR/tvdiary_purge $LDIR/tvdiary_purge
#ln -s $TDIR/tvdiary_publish $LDIR/tvdiary_publish
ln -s $TDIR/tvdiary_status $LDIR/tvdiary_status.jim
ln -s $TDIR/tvdiary_purge $LDIR/tvdiary_purge.jim
ln -s $TDIR/tvdiary_publish $LDIR/tvdiary_publish.jim
ln -s $TDIR/tvdiary_monitor_on $LDIR/tvdiary_monitor_on
ln -s $TDIR/tvdiary_monitor_off $LDIR/tvdiary_monitor_off

mkdir /mod/dev/tvdiary/live/webif
mkdir /mod/dev/tvdiary/live/webif/html
mkdir /mod/dev/tvdiary/live/webif/html/tvdiary

TDIR=/mod/webif/html/tvdiary
LDIR=/mod/dev/tvdiary/live/webif/html/tvdiary
ln -s $TDIR/calendar_params.jim $LDIR/calendar_params.jim
ln -s $TDIR/day_json.jim $LDIR/day_json.jim
ln -s $TDIR/dejavu_json.jim $LDIR/dejavu_json.jim
ln -s $TDIR/jslog.jim $LDIR/jslog.jim
ln -s $TDIR/index.shtml $LDIR/index.shtml
ln -s $TDIR/script.js $LDIR/script.js
ln -s $TDIR/style.css $LDIR/style.css
ln -s $TDIR/tvdiary_db.jim $LDIR/tvdiary_db.jim
ln -s $TDIR/tvmast.png $LDIR/tvmast.png

mkdir /mod/dev/tvdiary/live/webif/plugin
mkdir /mod/dev/tvdiary/live/webif/plugin/tvdiary

TDIR=/mod/webif/plugin/tvdiary
LDIR=/mod/dev/tvdiary/live/webif/plugin/tvdiary
ln -s $TDIR/icon.png $LDIR/icon.png
ln -s $TDIR/menu.hook $LDIR/menu.hook
ln -s $TDIR/settings.hook $LDIR/settings.hook
ln -s $TDIR/toolbar.hook $LDIR/toolbar.hook
ln -s $TDIR/update.jim $LDIR/update.jim

mkdir /mod/dev/tvdiary/live/etc
TDIR=/mod/etc
LDIR=/mod/dev/tvdiary/live/etc
ln -s $TDIR/tvdiary.conf $LDIR/tvdiary.conf
ln -s $TDIR/tvdiary.db $LDIR/tvdiary.db

mkdir /mod/dev/tvdiary/live/tmp
TDIR=/mod/tmp
LDIR=/mod/dev/tvdiary/live/tmp
ln -s $TDIR/tvdiary.log $LDIR/tvdiary.log
ln -s $TDIR/tvdiaryjs.log $LDIR/tvdiaryjs.log

mkdir /mod/dev/tvdiary/out
