#!/bin/sh

export tmpf=/tmp/cronf.$$

crontab=/mod/bin/crontab
if [ -x $crontab ]; then
  $crontab -l | grep -v tvdiary_status.jim > $tmpf
  [ -s $tmpf ] && $crontab $tmpf || $crontab -r
fi

[ -f $tmpf ] && rm -f $tmpf

exit 0
